name: run-tests
run-name: ${{ github.actor }}'s run.
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  paths:
      - 'pipeline/**'
jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install -r pipeline/requirements.txt

      - name: Install pytest
        run: pip install pytest

      - name: Run pytest
        run: pytest pipeline
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}

  lint_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install -r pipeline/requirements.txt

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        run: pylint pipeline/*.py --ignore-patterns=test_ --fail-under=8.5
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}